### PR TITLE
Remove roave/security-advisories

### PR DESCRIPTION
**Pull request by ralfkuehnel**

### CODE REVIEW

**Review by SanderVerkuil — APPROVED** [review]

**Comment by SanderVerkuil** [comment]
Thanks! It's also noted in my mermory as well. :-)

**Comment by ralfkuehnel** [comment]
Perfect, thanks! :)

I think that nyholm/symfony-bundle-test could be moved from "require" to "require-dev" section, it's not needed for production. What do you think?

Should i make a PR?

**Comment by SanderVerkuil** [comment]
I think that the nyholm/symfony-bundle-test is indeed not needed in production, just in the development of this project.

Sure, make a PR. I'll review it again ;)

Also, do you have any experience writing tests for a bundle like this? Because I don't really know how to test console commands and stuff like that, besides calling methods and testing those methods.

**Comment by ralfkuehnel** [comment]
Done, see #5 

Not really much experience, but I'll give it a try!

**Pull request merged**
